enableAllRules = true

[rule.add-constant]
Disabled = true

[rule.cognitive-complexity]
Arguments = [20]

[rule.cyclomatic]
Arguments = [20]

[rule.deep-exit]
Disabled = true

[rule.error-strings]
Disabled = true

[rule.flag-parameter]
Disabled = true

[rule.line-length-limit]
Arguments = [120]
